#!/bin/sh
#
# SPDX-FileCopyrightText: 2021 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only
#

. "$(dirname "$0")/_/husky.sh"

"$(dirname "$0")"/../node_modules/.bin/lint-staged
